split stdout and std error on list-all update dummy plugin to include error to ignore update broken plugin to add stderr output update list-all test to check for stderr on failure update list-all test to check for no stderr on success

diff --git a/test/fixtures/dummy_broken_plugin/bin/list-all b/test/fixtures/dummy_broken_plugin/bin/list-all
--- a/test/fixtures/dummy_broken_plugin/bin/list-all
+++ b/test/fixtures/dummy_broken_plugin/bin/list-all
@@ -1,4 +1,5 @@
 #!/usr/bin/env bash
 
-echo "List-all failed!"
+echo "Attempting to list versions"
+echo "List-all failed!" >&2
 exit 1
diff --git a/test/fixtures/dummy_plugin/bin/list-all b/test/fixtures/dummy_plugin/bin/list-all
--- a/test/fixtures/dummy_plugin/bin/list-all
+++ b/test/fixtures/dummy_plugin/bin/list-all
@@ -2,3 +2,5 @@
 
 versions_list=(1.0.0 1.1.0 2.0.0)
 echo "${versions_list[@]}"
+# Sending message to STD error to ensure that it is ignored
+echo "ignore this error" >&2
